language: python
python:
  - "3.6"

services:
  - postgresql

install:
  - pip install -r requirements.txt
  - python setup.py develop

script:
  - cd stackoverflow/api/v1
  - py.test --cov=stackoverflow tests/

after_success:
  - coveralls
